const express = require('express')
const sqlite3 = require('sqlite3').verbose()
const cors = require('cors')
const app = express()
const port = process.env.PORT || 3001
app.use(cors())
app.use(express.json())
const db = new sqlite3.Database('./calendar.db', err => { if(err) console.error(err) })
db.run('CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, start TEXT NOT NULL, end TEXT NOT NULL, color TEXT)')
app.get('/api/events',(req,res)=>{ db.all('SELECT * FROM events', [], (err,rows)=>{ if(err) return res.status(400).json({error:err.message}); res.json(rows) }) })
app.post('/api/events',(req,res)=>{ const {title,start,end,color}=req.body; db.run('INSERT INTO events (title,start,end,color) VALUES (?,?,?,?)',[title,start,end,color], function(err){ if(err) return res.status(400).json({error:err.message}); db.get('SELECT * FROM events WHERE id=?',[this.lastID], (e,row)=>{ if(e) return res.status(400).json({error:e.message}); res.json(row) }) }) })
app.put('/api/events/:id',(req,res)=>{ const {title,start,end,color}=req.body; db.run('UPDATE events SET title=?,start=?,end=?,color=? WHERE id=?',[title,start,end,color,req.params.id], function(err){ if(err) return res.status(400).json({error:err.message}); db.get('SELECT * FROM events WHERE id=?',[req.params.id], (e,row)=>{ if(e) return res.status(400).json({error:e.message}); res.json(row) }) }) })
app.delete('/api/events/:id',(req,res)=>{ db.run('DELETE FROM events WHERE id=?',[req.params.id], function(err){ if(err) return res.status(400).json({error:err.message}); res.json({id:parseInt(req.params.id)}) }) })
app.listen(port, ()=>{ console.log('server',port) })
